### ISSUE TITLE
Vue version miss-match

### ISSUE THREAD

**Issue by Gautam-Patel** [viralsolani/laravel-adminpanel#376] opened 2019-03-26 07:27 UTC
error  in ./resources/assets/js/components/Flash.vue
Module build failed
vue@2.6..8
vue-template-compiler@2.5.17

**Comment by bvipul** [comment] 2019-03-26 07:29
Please see #375

**Comment by chrizz1001** [comment] 2019-03-27 09:51
Hi, the fix #375 does not fix this for me. I tried to completely reinstall all node modules with the fix but still the same issue. I also tried complete fresh installation. Same issue...

**Comment by viralsolani** [comment] 2019-04-18 05:06
can you guys tell me your node version?

**Comment by viralsolani** [comment] 2019-04-19 11:04
the issue is fixed now. Please run _npm cache clear --force_.

**Closed by viralsolani** 2019-04-19 11:04 UTC
Labels: bug
