### ISSUE TITLE
registration not working

### ISSUE THREAD

**Issue by nithiyakumark** [viralsolani/laravel-adminpanel#219] opened 2018-05-07 02:16 UTC
hi, i'm trying to register an account but its not working even its not throwing any error

**Comment by viralsolani** [comment] 2018-05-08 05:12
@nithiyakumark Can you please report errors? If possible please provide screenshots?

**Comment by pervaiz04** [comment] 2018-05-20 11:49
same error with me - unable to register - no error - page refresh - seems not going in controller register function

**Comment by pervaiz04** [comment] 2018-05-20 11:51
alsi i am seeing this error
[Vue warn]: Unknown custom element: <flash> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)

**Comment by bvipul** [comment] 2018-06-19 07:12
Yes, @pervaiz04, thanks for pointing the issue, I will be resolving that in our next release.

**Comment by vrkansagara** [comment] 2018-07-05 19:05
@nithiyakumark and @pervaiz04 Kindly confirm the issue is still there.

**Comment by pervaiz04** [comment] 2018-07-05 19:11
Thank you for fixing,
I'll check shortly

Thanks

**Closed** 2018-07-07 10:51 UTC
