### ISSUE TITLE
Custom menu not working

### ISSUE THREAD

**Issue by netwrkx** [viralsolani/laravel-adminpanel#190] opened 2018-03-17 03:06 UTC
in reference to issue [151](https://github.com/viralsolani/laravel-adminpanel/issues/151), i just clone the project afresh and followed all instruction but everytime i try to add custom url it result to error "something went wrong try again".

**Comment by netwrkx** [comment] 2018-03-20 13:49
Anyone please!!

**Comment by bvipul** [comment] 2018-03-21 04:00
@netwrkx I think we have to use TeamViewer to actually look at what the problem is.... But we are in jobs, so it's difficult for us to do that. What is your timezone? So we can can fix a time to do this.

**Comment by netwrkx** [comment] 2018-03-21 22:43
Gmt +1

**Comment by bvipul** [comment] 2018-03-23 06:08
@netwrkx can we have a teamviewer session, at 6:00 PM GMT+1 time ? Would that work for you?
Thanks.

**Comment by netwrkx** [comment] 2018-03-23 13:20
Yes, its perfect

**Comment by bvipul** [comment] 2018-03-23 13:33
Okay, so please connect with me on hangouts, so we can share the IDs at that time.
My email is: basapativipulkumar@gmail.com

**Comment by netwrkx** [comment] 2018-03-23 16:06
ok

**Comment by bvipul** [comment] 2018-03-23 18:07
We just had a kind of teamviewer(anyDesk) session, and found that indeed it was a problem with our javascript for menu module and it was causing this error because of setTimeout value in one function, which I came to know in this session with @netwrkx. Thanks for that @netwrkx. I am happy that we actually found this and we have to solve this. I am closing this ticket and we will try to solve this ASAP @viralsolani @indranshastri .

**Closed by bvipul** 2018-03-23 18:07 UTC
