### ISSUE TITLE
Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required "     when new register then i found issue

### ISSUE THREAD

**Issue by himmat007** [viralsolani/laravel-adminpanel#422] opened 2019-08-06 09:22 UTC

**Comment by vrkansagara** [comment] 2019-09-03 04:13
@himmat007  Can you bit explain with step by step. You can use demo link for reproduce of this issue.

**Comment by krguptaa** [comment] 2019-12-06 05:19
We are closing this ticket. We are not able to reproduce. Please update us if you find any thing. We will reopen.

**Closed by krguptaa** 2019-12-06 05:19 UTC
Labels: awaiting author updates, hacktoberfest
