### ISSUE TITLE
Menu Module bug

### ISSUE THREAD

**Issue by netwrkx** [viralsolani/laravel-adminpanel#151] opened 2018-03-08 04:06 UTC
Hello, can you take a look at the menu module, adding custom menu url and edit already added menu isnt working, it display "something went wrong try again" then blank

![1](https://user-images.githubusercontent.com/5035044/37132502-476dc6e4-228e-11e8-97fb-50be1466dc00.PNG)
![2](https://user-images.githubusercontent.com/5035044/37132513-50696c62-228e-11e8-9869-554bd55eaf5d.PNG)
![3](https://user-images.githubusercontent.com/5035044/37132520-5af837b2-228e-11e8-97ba-e3c08e6f8f90.PNG)
![4](https://user-images.githubusercontent.com/5035044/37132521-5b638986-228e-11e8-883f-fb0be0deb61a.PNG)

**Comment by bvipul** [comment] 2018-03-09 05:49
Sorry @netwrkx I am not able to reproduce this. Can you maybe elaborate what were you trying to do while this happened?

**Comment by bvipul** [comment] 2018-03-09 07:22
@netwrkx I have been informed that, we have done some js work before a week or so. So can you, maybe update your installation (by git pull origin master) and running ``npm run dev``.

**Comment by netwrkx** [comment] 2018-03-10 14:43
It Didn't work, my project is up to date. What I'm trying to do is to add custom url but instead I get error "something went wrong try again"

**Comment by bvipul** [comment] 2018-03-14 14:11
Sorry bro, @netwrkx, I and one other Dev here are not able to reproduce. 
Hence I will have to close this ticket for now, but feel free to open it again.

**Closed** 2018-03-14 14:11 UTC
Labels: bug, needs Attention

**Comment by netwrkx** [comment] 2018-03-15 05:20
Problem still persist, I've done composer dumpautoload, php artisan cache:clear also php artisan clear, I've change browser from chrome to opera, yet problem persist.
